=== GithUbToolTest/soap/pojaxb/target/classes/po.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ip="http://www.ibm.com/product/sales" targetNamespace="http://www.ibm.com/product/sales">
	<xs:element name="purchase-order" type="ip:purchaseOrderType"/>
	<xs:complexType name="purchaseOrderType">
		<xs:sequence>
			<xs:element name="products" type="ip:productsType"/>
			<xs:element name="shipping-address" type="ip:shippingAddressType"/>
		</xs:sequence>
	</xs:complexType>	
	
	<xs:complexType name="productsType">
		<xs:sequence>
			<xs:element name="product" type="ip:productType" minOccurs="1" maxOccurs="unbounded"/>	
		</xs:sequence>
	</xs:complexType> 	
	
	<xs:complexType name="productType">
		<xs:sequence>
			<xs:element name="product-code" type="xs:string"/>
			<xs:element name="quantity" type="xs:int"/>
		</xs:sequence>	
	</xs:complexType>	
	
	<xs:complexType name="shippingAddressType">
		<xs:sequence>
				<xs:element name="address-line1" type="xs:string"/>
				<xs:element name="address-line2" type="xs:string"/>
				<xs:element name="zip-code" type="xs:int"/>	
				<xs:element name="state" type="xs:string"/>
				<xs:element name="country" type="xs:string"/>	
		</xs:sequence>
	</xs:complexType>	
</xs:schema>

=== GithUbToolTest/soap/pojaxb/src/main/resources/po.xml
<?xml version="1.0" encoding="UTF-8"?>
<ip:purchase-order xmlns:ip="http://www.ibm.com/product/sales" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ibm.com/product/sales file:///D:\SrimansirPractice\Web-Services\jax-b\pojaxb\src\main\resources\po.xsd">
	<products>
		<product>
			<product-code>HG2656</product-code>
			<quantity>10</quantity>
		</product>
	</products>
	<shipping-address>
		<address-line1>gauri  nagar</address-line1>
		<address-line2>near jai gurudev kirana</address-line2>
		<zip-code>452010</zip-code>
		<state>MP</state>
		<country>india</country>
	</shipping-address>

</ip:purchase-order>
